import {Page} from '../../components/Page';
import {useActiveProject,useAppStore} from '../../store/useAppStore';
import {machines,tools} from '../../data/catalog';
import {calculateProject} from '../../core/bending/calculations';

export function ProcessTreePage(){
 const project=useActiveProject(); const routes=useAppStore(s=>s.routes.filter(r=>r.projectId===project.id)); const welding=useAppStore(s=>s.welding.filter(w=>w.projectId===project.id)); const orders=useAppStore(s=>s.orders.filter(o=>o.projectId===project.id)); const machine=machines.find(m=>m.id===useAppStore.getState().selectedMachineId); const punch=tools.find(t=>t.id===useAppStore.getState().selectedPunchId); const die=tools.find(t=>t.id===useAppStore.getState().selectedDieId); const calc=calculateProject(project);
 const operations=[{name:'Material y chapa',detail:`${project.material} · ${project.thickness} mm · ${project.length} × ${project.width} mm`,state:'ready'},...[...project.bends].sort((a,b)=>a.order-b.order).map(b=>({name:`Plegado ${b.order}`,detail:`X ${b.position} · ${b.angle}° · R${b.radius} · ${b.side}`,state:b.punchId&&b.dieId?'ready':'warning'})),...welding.map(w=>({name:`Soldadura ${w.process}`,detail:`${w.joint} · ${w.length} mm · ${w.status}`,state:w.status==='completed'?'ready':'warning'}))];
 return <Page title="Árbol de fabricación" subtitle="Vista unificada del proyecto, operaciones, utillaje y liberación"><div className="process-tree-grid"><section className="panel process-tree"><div className="tree-root"><strong>{project.name}</strong><span>{project.customer}</span></div>{operations.map((op,i)=><article key={`${op.name}-${i}`} className={`tree-node ${op.state}`}><i>{i+1}</i><div><strong>{op.name}</strong><small>{op.detail}</small></div></article>)}</section><aside className="panel process-summary"><h3>Contexto industrial</h3><dl><div><dt>Máquina</dt><dd>{machine?`${machine.manufacturer} ${machine.name}`:'Sin asignar'}</dd></div><div><dt>Montaje</dt><dd>{punch?.name} / {die?.name}</dd></div><div><dt>Peso</dt><dd>{calc.weightKg.toFixed(2)} kg</dd></div><div><dt>Desarrollo</dt><dd>{calc.estimatedFlatLength.toFixed(2)} mm</dd></div><div><dt>Rutas</dt><dd>{routes.length}</dd></div><div><dt>Órdenes</dt><dd>{orders.length}</dd></div></dl><h3>Rutas liberadas</h3>{routes.length?<ul className="simple-list">{routes.map(r=><li key={r.id}><b>{r.name}</b><span>{r.steps.length} pasos · {r.status}</span></li>)}</ul>:<p className="muted">Todavía no hay rutas guardadas para este proyecto.</p>}</aside></div></Page>
}
