import {useMemo,useRef,useState} from 'react';
import type {PointerEvent as ReactPointerEvent,WheelEvent as ReactWheelEvent} from 'react';
import {Page} from '../../components/Page';
import {useActiveProject,useAppStore} from '../../store/useAppStore';
import {tools} from '../../data/catalog';

type View='isometric'|'front'|'side'|'top';
export function Programming3DPage(){
  const p=useActiveProject();
  const addBend=useAppStore(s=>s.addBend),updateBend=useAppStore(s=>s.updateBend),removeBend=useAppStore(s=>s.removeBend),reorderBend=useAppStore(s=>s.reorderBend);
  const [view,setView]=useState<View>('isometric');const [dimensions,setDimensions]=useState(true);const [zoom,setZoom]=useState(1);const [rotationX,setRotationX]=useState(-10);const [rotationY,setRotationY]=useState(-22);const [pan,setPan]=useState({x:0,y:0});const [selected,setSelected]=useState(p.bends[0]?.id??'');
  const drag=useRef<{x:number;y:number;pan:boolean}|null>(null);
  const touches=useRef(new Map<number,{x:number;y:number}>());
  const pinch=useRef<{distance:number;zoom:number;midX:number;midY:number;panX:number;panY:number}|null>(null);
  const [position,setPosition]=useState(Math.round(p.length/2));const [length,setLength]=useState(p.width);const [angle,setAngle]=useState(90);const [radius,setRadius]=useState(Math.max(1,p.thickness));const [side,setSide]=useState<'interior'|'exterior'>('interior');const [direction,setDirection]=useState<'positive'|'negative'>('positive');
  const punch=tools.find(t=>t.kind==='punch')!,die=tools.find(t=>t.kind==='die')!;const bend=useMemo(()=>p.bends.find(b=>b.id===selected),[p.bends,selected]);
  const create=()=>{if(position<=0||position>=p.length||length<=0)return;addBend({position,length:Math.min(length,p.width),angle,radius,side,direction,fixedFace:'left',punchId:punch.id,dieId:die.id,backgaugeX:position,correction:0})};
  const reset=()=>{setView('isometric');setZoom(1);setRotationX(-10);setRotationY(-22);setPan({x:0,y:0})};
  const applyView=(next:View)=>{setView(next);const presets={isometric:[-10,-22],front:[0,0],side:[0,-90],top:[-90,0]} as const;setRotationX(presets[next][0]);setRotationY(presets[next][1])};
  const onPointerDown=(event:ReactPointerEvent)=>{touches.current.set(event.pointerId,{x:event.clientX,y:event.clientY});event.currentTarget.setPointerCapture(event.pointerId);if(touches.current.size===1)drag.current={x:event.clientX,y:event.clientY,pan:event.shiftKey||event.button===1};if(touches.current.size===2){const [a,b]=[...touches.current.values()];pinch.current={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom,midX:(a.x+b.x)/2,midY:(a.y+b.y)/2,panX:pan.x,panY:pan.y};drag.current=null}};
  const onPointerMove=(event:ReactPointerEvent)=>{if(touches.current.has(event.pointerId))touches.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(touches.current.size===2&&pinch.current){const [a,b]=[...touches.current.values()];const distance=Math.max(20,Math.hypot(a.x-b.x,a.y-b.y));const midX=(a.x+b.x)/2,midY=(a.y+b.y)/2;setZoom(Math.max(.42,Math.min(2.4,pinch.current.zoom*distance/pinch.current.distance)));setPan({x:pinch.current.panX+(midX-pinch.current.midX),y:pinch.current.panY+(midY-pinch.current.midY)});return}if(!drag.current)return;const dx=event.clientX-drag.current.x,dy=event.clientY-drag.current.y;if(drag.current.pan)setPan(v=>({x:v.x+dx,y:v.y+dy}));else{setRotationY(v=>v+dx*.5);setRotationX(v=>Math.max(-100,Math.min(75,v-dy*.4)))}drag.current={...drag.current,x:event.clientX,y:event.clientY}};
  const stopDrag=(event:ReactPointerEvent)=>{touches.current.delete(event.pointerId);if(touches.current.size<2)pinch.current=null;if(touches.current.size===1){const point=[...touches.current.values()][0];drag.current={...point,pan:false}}else drag.current=null;try{event.currentTarget.releasePointerCapture(event.pointerId)}catch{/*noop*/}};
  const onWheel=(event:ReactWheelEvent)=>{event.preventDefault();setZoom(v=>Math.max(.42,Math.min(2.4,v*(event.deltaY<0?1.12:.88))))};
  return <Page title="Programación 3D" subtitle="Programar plegados y comprobar la pieza con control táctil, cámara libre y cotas">
    <div className="engineering-grid">
      <section className="viewer panel programming3d-viewer interactive-3d" onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={stopDrag} onPointerCancel={stopDrag} onWheel={onWheel} onDoubleClick={reset}>
        <div className="part3d free-camera" style={{'--folds':p.bends.length,transform:`translate3d(${pan.x}px,${pan.y}px,0) scale(${zoom}) rotateX(${rotationX}deg) rotateY(${rotationY}deg)`} as React.CSSProperties}><div className="face base"/>{p.bends.map((b,i)=><div key={b.id} className={`face dynamic-flange ${b.direction}`} style={{left:`${Math.max(8,Math.min(84,b.position/p.length*100))}%`,transform:`rotateY(${(b.direction==='negative'?-1:1)*Math.min(88,b.angle)}deg) translateZ(${i*4}px)`}}><span>P{b.order}</span></div>)}</div>
        <div className="viewer-tools"><button type="button" className={view==='isometric'?'active':''} onClick={()=>applyView('isometric')}>Isométrica</button><button type="button" className={view==='front'?'active':''} onClick={()=>applyView('front')}>Frontal</button><button type="button" className={view==='side'?'active':''} onClick={()=>applyView('side')}>Lateral</button><button type="button" className={view==='top'?'active':''} onClick={()=>applyView('top')}>Superior</button><button type="button" onClick={()=>setRotationY(r=>r-15)}>Girar ↶</button><button type="button" onClick={()=>setRotationY(r=>r+15)}>Girar ↷</button><button type="button" onClick={reset}>Centrar</button><button type="button" className={dimensions?'active':''} onClick={()=>setDimensions(v=>!v)}>{dimensions?'Ocultar cotas':'Mostrar cotas'}</button><button type="button" onClick={()=>setZoom(z=>Math.min(2.4,z+.12))}>Acercar</button><button type="button" onClick={()=>setZoom(z=>Math.max(.42,z-.12))}>Alejar</button></div>
        <div className="viewport-help">Arrastrar: girar · dos dedos: zoom y mover · Mayús + arrastrar: desplazar · doble clic: centrar</div>
        {dimensions&&<div className="dimension-strip"><span>L {p.length} mm</span><span>A {p.width} mm</span><span>e {p.thickness} mm</span>{p.bends.map(b=><span key={b.id}>P{b.order}: X{b.position} · L{b.length} · {b.angle}° · R{b.radius} · {b.side}</span>)}</div>}
      </section>
      <aside className="panel form programming-form"><h3>Nuevo plegado</h3><div className="form-grid"><label>Posición X<input type="number" value={position} min="1" max={p.length-1} onChange={e=>setPosition(Number(e.target.value))}/></label><label>Longitud<input type="number" value={length} min="1" max={p.width} onChange={e=>setLength(Number(e.target.value))}/></label><label>Ángulo<input type="number" value={angle} min="1" max="179" onChange={e=>setAngle(Number(e.target.value))}/></label><label>Radio interior<input type="number" step="0.1" value={radius} onChange={e=>setRadius(Number(e.target.value))}/></label><label>Tipo<select value={side} onChange={e=>setSide(e.target.value as typeof side)}><option value="interior">Interior</option><option value="exterior">Exterior</option></select></label><label>Sentido<select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="positive">Positivo</option><option value="negative">Negativo</option></select></label></div><button type="button" onClick={create}>Añadir plegado y actualizar pieza</button><h3>Secuencia</h3><div className="rows">{p.bends.map(b=><button type="button" key={b.id} className={`bend-row ${selected===b.id?'selected':''}`} onClick={()=>setSelected(b.id)}><b>P{b.order}</b><span>X {b.position} · L {b.length} · {b.angle}° · R{b.radius}</span><span>{b.side}</span></button>)}</div>{bend&&<div className="form"><h3>Editar P{bend.order}</h3><div className="form-grid"><label>Ángulo<input type="number" value={bend.angle} onChange={e=>updateBend(bend.id,{angle:Number(e.target.value)})}/></label><label>Posición<input type="number" value={bend.position} onChange={e=>updateBend(bend.id,{position:Number(e.target.value),backgaugeX:Number(e.target.value)})}/></label><label>Longitud<input type="number" value={bend.length} onChange={e=>updateBend(bend.id,{length:Number(e.target.value)})}/></label><label>Radio<input type="number" step="0.1" value={bend.radius} onChange={e=>updateBend(bend.id,{radius:Number(e.target.value)})}/></label></div><div className="form-actions"><button type="button" onClick={()=>reorderBend(bend.id,-1)}>Subir</button><button type="button" onClick={()=>reorderBend(bend.id,1)}>Bajar</button><button type="button" className="danger" onClick={()=>{removeBend(bend.id);setSelected('')}}>Eliminar</button></div></div>}</aside>
    </div>
  </Page>
}
