import {useEffect,useMemo,useState} from 'react';
import {Page} from '../../components/Page';

type Category='general'|'navigation'|'precision'|'engineering'|'graphics'|'simulation'|'data'|'system';
type Settings={
 theme:'dark'|'system';accent:'cyan'|'blue'|'violet';scale:number;animations:boolean;animationSpeed:'fast'|'normal'|'relaxed';startupSplash:boolean;splashSeconds:number;
 showBack:boolean;showForward:boolean;preserveCamera:boolean;rememberModule:boolean;confirmExit:boolean;openLastProject:boolean;touchTarget:number;
 units:'mm'|'in';decimals:number;angleDecimals:number;linearTolerance:number;angleTolerance:number;radiusTolerance:number;showValueOrigin:boolean;snapPrecision:number;
 kFactor:number;yFactor:number;vRule:number;defaultRadius:number;springback:number;calculationMethod:'k-factor'|'bend-deduction'|'table';defaultMachine:string;defaultMaterial:string;
 graphics:'performance'|'balanced'|'maximum';renderScale:number;fps:number;antialias:boolean;shadows:boolean;reflections:boolean;ambientOcclusion:boolean;textureQuality:'low'|'medium'|'high';lod:'low'|'medium'|'high';pauseBackground:boolean;
 collision:boolean;stopOnCollision:boolean;dimensions:boolean;keepFinalPart:boolean;autoCamera:boolean;simulationSpeed:number;pauseBetweenSteps:number;showBackgauge:boolean;showForce:boolean;showAxes:boolean;
 autosave:number;backupCopies:number;confirmDeletes:boolean;protectOriginal:boolean;offlineMode:boolean;dailyLibraries:boolean;diagnosticLogs:boolean;
 notifications:boolean;chat:boolean;sound:boolean;telemetry:boolean;language:'es'|'en';dateFormat:string;
};
const defaults:Settings={theme:'dark',accent:'cyan',scale:100,animations:true,animationSpeed:'normal',startupSplash:true,splashSeconds:5,showBack:true,showForward:true,preserveCamera:true,rememberModule:true,confirmExit:true,openLastProject:true,touchTarget:44,units:'mm',decimals:2,angleDecimals:1,linearTolerance:.1,angleTolerance:.5,radiusTolerance:.1,showValueOrigin:true,snapPrecision:.1,kFactor:.38,yFactor:.5,vRule:8,defaultRadius:2,springback:1,calculationMethod:'k-factor',defaultMachine:'TRUMPF TrumaBend V85',defaultMaterial:'S235JR',graphics:'balanced',renderScale:100,fps:60,antialias:true,shadows:true,reflections:true,ambientOcclusion:true,textureQuality:'high',lod:'high',pauseBackground:true,collision:true,stopOnCollision:true,dimensions:true,keepFinalPart:true,autoCamera:false,simulationSpeed:1,pauseBetweenSteps:.4,showBackgauge:true,showForce:true,showAxes:true,autosave:30,backupCopies:10,confirmDeletes:true,protectOriginal:true,offlineMode:true,dailyLibraries:false,diagnosticLogs:true,notifications:true,chat:true,sound:true,telemetry:false,language:'es',dateFormat:'dd/MM/yyyy'};
const categories:[Category,string,string][]=[['general','General','Apariencia, escala y pantalla inicial'],['navigation','Navegación','Volver, Adelante, historial y controles táctiles'],['precision','Medición y precisión','Unidades, decimales, tolerancias y ajuste'],['engineering','Ingeniería','Cálculo de plegado y valores predeterminados'],['graphics','Gráficos 3D','Calidad, GPU, sombras y rendimiento'],['simulation','Simulación','Movimiento, colisiones, cotas y cámara'],['data','Datos y copias','Guardado, restauración y bibliotecas'],['system','Sistema','Idioma, avisos y diagnóstico']];

export function SettingsPage(){
 const [settings,setSettings]=useState<Settings>(()=>{try{return{...defaults,...JSON.parse(localStorage.getItem('plegar-pro-settings')||'{}')}}catch{return defaults}});
 const [category,setCategory]=useState<Category>('general');const [saved,setSaved]=useState(false);const [query,setQuery]=useState('');const [message,setMessage]=useState('');
 useEffect(()=>{document.documentElement.style.setProperty('--ui-scale',String(settings.scale/100));document.documentElement.style.setProperty('--touch-target',`${settings.touchTarget}px`);document.documentElement.dataset.animations=String(settings.animations);document.documentElement.dataset.accent=settings.accent},[settings.scale,settings.touchTarget,settings.animations,settings.accent]);
 const set=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(s=>({...s,[key]:value}));
 const save=()=>{localStorage.setItem('plegar-pro-settings',JSON.stringify(settings));setSaved(true);setTimeout(()=>setSaved(false),1600)};
 const exportConfig=()=>{const blob=new Blob([JSON.stringify(settings,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='plegar-pro-ajustes.json';a.click();URL.revokeObjectURL(a.href)};
 const importConfig=async(file:File|null)=>{if(!file)return;try{setSettings({...defaults,...JSON.parse(await file.text())});setMessage('Configuración importada. Pulsa Guardar todo.')}catch{setMessage('Archivo de configuración no válido.')}};
 const visibleCategories=useMemo(()=>query.trim()?categories.filter(([,name,description])=>`${name} ${description}`.toLowerCase().includes(query.toLowerCase())):categories,[query]);
 const number=(key:keyof Settings,label:string,min:number,max:number,step:number,unit='')=><label>{label}<span className="setting-input-row"><input type="number" min={min} max={max} step={step} value={settings[key] as number} onChange={e=>set(key,Number(e.target.value) as never)}/>{unit&&<b>{unit}</b>}</span></label>;
 const check=(key:keyof Settings,label:string,help?:string)=><label className="check-row"><span>{label}{help&&<small>{help}</small>}</span><input type="checkbox" checked={Boolean(settings[key])} onChange={e=>set(key,e.target.checked as never)}/></label>;
 return <Page title="Ajustes profesionales" subtitle="Configuración completa del programa, precisión industrial, gráficos, simulación y seguridad" actions={<div className="settings-actions"><button type="button" className="primary" onClick={save}>{saved?'Guardado ✓':'Guardar todo'}</button><button type="button" onClick={exportConfig}>Exportar</button><label className="file-button">Importar<input type="file" accept=".json" onChange={e=>importConfig(e.target.files?.[0]??null)}/></label><button type="button" className="danger" onClick={()=>{setSettings(defaults);setMessage('Valores predeterminados cargados. Pulsa Guardar todo.')}}>Restablecer</button></div>}>
  {message&&<section className="panel notice"><p>{message}</p></section>}
  <div className="settings-pro-layout">
   <aside className="panel settings-index"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ajustes…"/>{visibleCategories.map(([id,name,description])=><button type="button" key={id} className={category===id?'active':''} onClick={()=>setCategory(id)}><strong>{name}</strong><small>{description}</small></button>)}</aside>
   <section className="panel settings-workspace">
    {category==='general'&&<><h2>General y apariencia</h2><div className="settings-section-grid"><label>Tema<select value={settings.theme} onChange={e=>set('theme',e.target.value as Settings['theme'])}><option value="dark">Oscuro industrial</option><option value="system">Según el sistema</option></select></label><label>Color principal<select value={settings.accent} onChange={e=>set('accent',e.target.value as Settings['accent'])}><option value="cyan">Cian técnico</option><option value="blue">Azul industrial</option><option value="violet">Violeta CAD</option></select></label>{number('scale','Escala de interfaz',80,140,1,'%')}<label>Velocidad de animación<select value={settings.animationSpeed} onChange={e=>set('animationSpeed',e.target.value as Settings['animationSpeed'])}><option value="fast">Rápida</option><option value="normal">Normal</option><option value="relaxed">Suave</option></select></label>{check('animations','Animaciones de interfaz')}{check('startupSplash','Logo y barra de carga al iniciar')}{number('splashSeconds','Duración de la carga',1,10,1,'s')}</div></>}
    {category==='navigation'&&<><h2>Navegación y controles</h2><div className="settings-section-grid">{check('showBack','Mostrar ← Volver en todas las pantallas')}{check('showForward','Mostrar → Adelante')}{check('preserveCamera','Conservar cámara, zoom y selección al volver')}{check('rememberModule','Recordar el último módulo abierto')}{check('confirmExit','Avisar si hay cambios sin guardar')}{check('openLastProject','Abrir el último proyecto al iniciar')}{number('touchTarget','Tamaño mínimo de controles táctiles',36,64,1,'px')}</div></>}
    {category==='precision'&&<><h2>Medición y precisión</h2><div className="settings-section-grid"><label>Unidades<select value={settings.units} onChange={e=>set('units',e.target.value as Settings['units'])}><option value="mm">Milímetros</option><option value="in">Pulgadas</option></select></label>{number('decimals','Decimales lineales',0,4,1)}{number('angleDecimals','Decimales angulares',0,3,1)}{number('linearTolerance','Tolerancia lineal',0,10,.01,settings.units)}{number('angleTolerance','Tolerancia angular',0,10,.1,'°')}{number('radiusTolerance','Tolerancia de radio',0,10,.01,settings.units)}{number('snapPrecision','Precisión de ajuste magnético',.001,10,.001,settings.units)}{check('showValueOrigin','Indicar si el valor es nominal, calculado, medido o calibrado')}</div><p className="settings-note">Los decimales controlan la presentación. La exactitud física depende de material, espesor real, máquina, punzón, matriz, apertura V y calibración del taller.</p></>}
    {category==='engineering'&&<><h2>Ingeniería de plegado</h2><div className="settings-section-grid"><label>Método de desarrollo<select value={settings.calculationMethod} onChange={e=>set('calculationMethod',e.target.value as Settings['calculationMethod'])}><option value="k-factor">Factor K</option><option value="bend-deduction">Deducción de plegado</option><option value="table">Tabla calibrada del taller</option></select></label>{number('kFactor','Factor K',.1,.8,.001)}{number('yFactor','Factor Y',.1,1,.001)}{number('vRule','Regla V / espesor',4,16,.1)}{number('defaultRadius','Radio interior predeterminado',.1,100,.1,settings.units)}{number('springback','Compensación de recuperación',0,15,.1,'°')}<label>Material por defecto<input value={settings.defaultMaterial} onChange={e=>set('defaultMaterial',e.target.value)}/></label><label>Máquina por defecto<input value={settings.defaultMachine} onChange={e=>set('defaultMachine',e.target.value)}/></label></div></>}
    {category==='graphics'&&<><h2>Gráficos 3D y rendimiento</h2><div className="settings-section-grid"><label>Perfil<select value={settings.graphics} onChange={e=>set('graphics',e.target.value as Settings['graphics'])}><option value="performance">Rendimiento</option><option value="balanced">Equilibrado</option><option value="maximum">Máxima calidad</option></select></label>{number('renderScale','Escala de render',50,150,5,'%')}{number('fps','FPS máximos',15,120,5)}<label>Texturas<select value={settings.textureQuality} onChange={e=>set('textureQuality',e.target.value as Settings['textureQuality'])}><option value="low">Bajas</option><option value="medium">Medias</option><option value="high">Altas</option></select></label><label>Nivel de detalle<select value={settings.lod} onChange={e=>set('lod',e.target.value as Settings['lod'])}><option value="low">Bajo</option><option value="medium">Medio</option><option value="high">Alto</option></select></label>{check('antialias','Antialiasing')}{check('shadows','Sombras suaves')}{check('reflections','Reflejos metálicos')}{check('ambientOcclusion','Oclusión ambiental')}{check('pauseBackground','Pausar renderizado en segundo plano')}</div></>}
    {category==='simulation'&&<><h2>Simulación 2D y 3D</h2><div className="settings-section-grid">{check('collision','Detección de colisiones')}{check('stopOnCollision','Detener la máquina ante una colisión')}{check('dimensions','Mostrar cotas durante la simulación')}{check('keepFinalPart','Mantener la pieza final visible')}{check('autoCamera','Cámara automática entre pasos')}{check('showBackgauge','Mostrar topes traseros')}{check('showForce','Mostrar fuerza y tonelaje')}{check('showAxes','Mostrar ejes X, R, Z e Y')}{number('simulationSpeed','Velocidad predeterminada',.25,4,.25,'×')}{number('pauseBetweenSteps','Pausa entre pasos',0,5,.1,'s')}</div></>}
    {category==='data'&&<><h2>Datos, copias y bibliotecas</h2><div className="settings-section-grid">{number('autosave','Guardado automático',5,600,5,'s')}{number('backupCopies','Número máximo de copias',1,100,1)}{check('confirmDeletes','Confirmar eliminaciones')}{check('protectOriginal','Proteger archivos importados originales')}{check('offlineMode','Modo sin conexión')}{check('dailyLibraries','Comprobar bibliotecas diariamente')}{check('diagnosticLogs','Guardar registros técnicos de diagnóstico')}</div></>}
    {category==='system'&&<><h2>Sistema y comunicaciones</h2><div className="settings-section-grid"><label>Idioma<select value={settings.language} onChange={e=>set('language',e.target.value as Settings['language'])}><option value="es">Español</option><option value="en">English</option></select></label><label>Formato de fecha<input value={settings.dateFormat} onChange={e=>set('dateFormat',e.target.value)}/></label>{check('notifications','Notificaciones')}{check('chat','Chat técnico interno')}{check('sound','Sonidos de interfaz y simulación')}{check('telemetry','Telemetría voluntaria')}</div><div className="diagnostic-summary"><strong>Diagnóstico rápido</strong><span>Versión: 0.24.4</span><span>Almacenamiento local: disponible</span><span>WebGL: se comprobará al abrir un visor 3D</span></div></>}
   </section>
  </div>
 </Page>;
}
